"""
Seed Database of 50+ Known Canonical AI Startups and Organizations
Used for deterministic entity resolution, alias mapping, and deduplication.
"""

from typing import Dict, List

CANONICAL_SEED_COMPANIES: Dict[str, List[str]] = {
    "OpenAI": ["OpenAI, Inc.", "Open AI", "OpenAI LLC", "OpenAI Research", "OpenAI Global"],
    "Anthropic": ["Anthropic PBC", "Anthropic, Inc.", "Anthropic AI", "Anthropic Research"],
    "Mistral AI": ["Mistral", "Mistral AI SAS", "Mistral.ai", "Mistral Labs"],
    "Cohere": ["Cohere Inc.", "Cohere AI", "Cohere Technologies"],
    "Scale AI": ["Scale", "Scale AI, Inc.", "Scale.com", "Scale Labs"],
    "Hugging Face": ["Hugging Face, Inc.", "HuggingFace", "HuggingFace Inc", "HF Labs"],
    "Databricks": ["Databricks, Inc.", "Databricks Inc", "Databricks MosaicML", "MosaicML"],
    "Perplexity AI": ["Perplexity", "Perplexity, Inc.", "Perplexity.ai", "Perplexity Labs"],
    "Midjourney": ["Midjourney, Inc.", "Midjourney Research", "Midjourney Labs"],
    "Stability AI": ["Stability AI Ltd", "Stability.ai", "Stability AI Inc", "Stability"],
    "ElevenLabs": ["ElevenLabs Inc.", "Eleven Labs", "ElevenLabs.io", "ElevenMultilingual"],
    "Runway": ["Runway AI", "RunwayML", "Runway AI, Inc.", "Runway Research"],
    "Character.ai": ["Character AI", "Character Technologies, Inc.", "Character.AI", "c.ai"],
    "Together AI": ["Together Computer, Inc.", "Together", "Together.ai", "Together Labs"],
    "Groq": ["Groq, Inc.", "Groq Inc", "Groq Hardware", "Groq AI"],
    "DeepSeek": ["DeepSeek AI", "DeepSeek-AI", "Hangzhou DeepSeek", "DeepSeek Research"],
    "Anysphere (Cursor)": ["Cursor", "Anysphere, Inc.", "Cursor AI", "Anysphere"],
    "Cognition AI": ["Cognition Labs", "Cognition", "Devin AI", "Cognition AI, Inc."],
    "Harvey AI": ["Harvey", "Harvey, Inc.", "Harvey Legal AI", "Counsel AI Inc"],
    "Glean": ["Glean Technologies, Inc.", "Glean Search", "Glean AI"],
    "Synthesia": ["Synthesia Ltd", "Synthesia.io", "Synthesia AI"],
    "Pika Labs": ["Pika", "Pika Art", "Pika Labs, Inc.", "Pika.art"],
    "Writer": ["Writer, Inc.", "Writer.com", "Writer AI"],
    "Jasper": ["Jasper AI", "Jasper.ai", "Jasper Inc", "UseJasper"],
    "Pinecone": ["Pinecone Systems, Inc.", "Pinecone Vector Database", "Pinecone.io"],
    "Qdrant": ["Qdrant Solutions GmbH", "Qdrant Vector DB", "Qdrant.tech"],
    "Weaviate": ["Weaviate B.V.", "Weaviate.io", "Weaviate Vector Search"],
    "Chroma": ["Chroma Inc.", "Chroma DB", "ChromaDB", "TryChroma"],
    "LangChain": ["LangChain, Inc.", "LangChain Inc", "LangChain AI", "LangSmith"],
    "LlamaIndex": ["LlamaIndex, Inc.", "GPT Index", "Llama Index"],
    "Weights & Biases": ["W&B", "Weights and Biases, Inc.", "wandb", "Weights & Biases Inc"],
    "Replicate": ["Replicate, Inc.", "Replicate.com", "Replicate AI"],
    "Fireworks AI": ["Fireworks.ai", "Fireworks AI, Inc.", "Fireworks"],
    "Physical Intelligence": ["Pi", "Physical Intelligence, Inc.", "Physical AI"],
    "Figure AI": ["Figure", "Figure 01", "Figure AI, Inc."],
    "Covariant": ["Covariant.ai", "Covariant, Inc."],
    "Adept AI": ["Adept", "Adept AI Labs, Inc.", "Adept Labs"],
    "Inflection AI": ["Inflection", "Inflection AI, Inc.", "Pi.ai"],
    "Poolside": ["Poolside AI", "Poolside, Inc.", "Poolside Labs"],
    "Cerebras Systems": ["Cerebras", "Cerebras Systems, Inc.", "Cerebras AI"],
    "SambaNova Systems": ["SambaNova", "SambaNova Systems, Inc."],
    "Tenstorrent": ["Tenstorrent Inc.", "Tenstorrent AI"],
    "Lambda": ["Lambda Labs", "Lambda Labs, Inc.", "Lambda GPU Cloud"],
    "CoreWeave": ["CoreWeave, Inc.", "CoreWeave Cloud"],
    "Crusoe Energy": ["Crusoe", "Crusoe Cloud", "Crusoe Energy Systems"],
    "Vast.ai": ["Vast AI", "Vast.ai, Inc."],
    "Tabnine": ["Tabnine Ltd", "Codota", "Tabnine AI"],
    "Codeium": ["Exafunction, Inc.", "Codeium AI", "Exafunction"],
    "Baseten": ["Baseten, Inc.", "Baseten.co", "Baseten Labs"],
    "Modal": ["Modal Labs, Inc.", "Modal Labs", "Modal.com"]
}
